name: Katarina
favicon: null
layout_spectrum: 0.20544385188259184
typography_spectrum: 0.915279250824824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f5e2de'
    - '#efd0cb'
    - '#e9b8b1'
    - '#ce9287'
  brandStrength: 0.625
  lightness: 0.09210924571380019
  saturation: 0.6875
  rhythmicContrast: 0.9409320435952395
purpose: []
